### ISSUE TITLE
Write after end error

### ISSUE THREAD

**Issue by jghaanstra** [biancode/node-modbus#19]
I'm reading out my solar inverter over modbus interface. My current script reads out 4 holding registers in a nested function where the next holding register is read when the previous is done. Simply put it looks like this.

```
client.readHoldingRegisters(30775, 2).then((resp) => {
  // do something with resp.payload
}).catch((err) => {
  console.log(err);
}).done(() => {

  client.readHoldingRegisters(30517, 4).then((resp) => {
    // do something with resp.payload
  }).catch((err) => {
    console.log(err);
  }).done(() => {

    client.readHoldingRegisters(30783, 2).then((resp) => {
      // do something with resp.payload
    }).catch((err) => {
      console.log(err);
    }).done(() => {

      client.readHoldingRegisters(30513, 4).then((resp) => {
        // do something with resp.payload
      }).catch((err) => {
        console.log(err);
      })

    })
  })
})
```

At some point I get a time out error when reading out one of the registers. I dont know why, it's  wired connection on a stable network but I would assume the script would catch the error and wont continu in the done() function. I handle the catched error by closing the client connection and reconnecting in one minute. However, looking at the log it seems the script still read out the next register even though a time out error was catched. See the log below.

```
Connected ...
{ err: 'timeout' }
2018-09-01 11:24:47 [log] [ManagerDrivers] [inverter] [0] Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at Socket.Writable.write (_stream_writable.js:287:5)
    at Socket.write (net.js:704:40)
    at Object.<anonymous> (/node_modules/node-modbus/node-modbus/modbus-tcp-client.js:1:2318)
    at Object.emit (/node_modules/stampit-event-bus/src/stampit-event-bus.js:20:38)
    at Object.<anonymous> (/node_modules/node-modbus/node-modbus/modbus-client-core.js:1:1047)
    at Object.queueRequest (/node_modules/node-modbus/node-modbus/modbus-client-core.js:1:2591)
    at Object.<anonymous> (/node_modules/node-modbus/node-modbus/handler/client/ReadHoldingRegisters.js:1:961)
    at Promise._execute (/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/node_modules/bluebird/js/release/promise.js:79:10)
    at Object.readHoldingRegisters (/node_modules/node-modbus/node-modbus/handler/client/ReadHoldingRegisters.js:1:844)
    at client.readHoldingRegisters.then.catch.done (/drivers/inverter/device.js:62:20)
    at tryCatcher (/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/node_modules/bluebird/js/release/promise.js:569:18)
Client closed, retrying in 60 seconds
Reconnecting now ...
Connected ...
```

And last but not least. After the initial time out error the script keeps reporting this error as if it's not capable of reconnection even though the client.close() was called and new connection was started. The only way to get a working connection is to stop/start the script. This last error looks a lot like the issue described here: https://github.com/biancode/node-modbus/issues/5 . But this is supposed to be fixed.

I would really appreciate it if someone could help me fix this so time out errors dont result in endless loops of new time out errors.

**Comment by jghaanstra** [comment]
Nevermind, just saw the notice of this library not being maintained anymore.
